// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8PR9UuHOn9S9ioTEHw1Y-2-g4C2A5J6s',
    appId: '1:1008209446719:android:69cde8d01387916155f58a',
    messagingSenderId: '1008209446719',
    projectId: 'deep-mantra',
    storageBucket: 'deep-mantra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmhY0ZY1f6BYJRbrqbjK1WNucX_yVQwpU',
    appId: '1:1008209446719:ios:a993a1a14ccea54155f58a',
    messagingSenderId: '1008209446719',
    projectId: 'deep-mantra',
    iosBundleId: 'com.deepmantra.deepMantra',
    storageBucket: 'deep-mantra.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmhY0ZY1f6BYJRbrqbjK1WNucX_yVQwpU',
    appId: '1:1008209446719:ios:a993a1a14ccea54155f58a',
    messagingSenderId: '1008209446719',
    projectId: 'deep-mantra',
    iosBundleId: 'com.deepmantra.deepMantra',
    storageBucket: 'deep-mantra.firebasestorage.app',
  );
}
